### ISSUE TITLE
Codesanbox in article not working

### ISSUE THREAD

**Issue by ries9112** [Robpayot/risograph-grain-shader#1]
Such a cool tutorial! Just wanted to flag that the codesanbox environments embedded throughout don't seem to be working right now:
<img width="837" alt="image" src="https://user-images.githubusercontent.com/32306488/224521081-a8f18af9-7d44-4d7b-a840-d09238eb382c.png">

Just wanted to let you know in case you weren't already aware 🙂

**Comment by Robpayot** [comment]
Hello, thanks for notifying!

However I think the reason of this error is the device you are using. I
think it is not able to support WebGL for some reason.

It seems to work fine for me on my iPhone and desktop

Maybe you should try on another device and let me know.

Cheers

**Comment by ries9112** [comment]
ohh gotcha sorry about that! You are right, it was my web browser that wasn't liking it, a different browser on same macbook works 👌
